export const adminActionTypes = {
  //GET ADMINS SECTION
  GET_ADMINS_START: 'GET_ADMINS_START',
  GET_ADMINS_END: 'GET_ADMINS_END',
  GET_ADMINS_SUCCESS: 'GET_ADMINS_SUCCESS',
  GET_ADMINS_FAILURE: 'GET_ADMINS_FAILURE',
  //GET ADMIN SECTION
  GET_ADMIN_START: 'GET_ADMIN_START',
  GET_ADMIN_END: 'GET_ADMIN_END',
  GET_ADMIN_SUCCESS: 'GET_ADMIN_SUCCESS',
  GET_ADMIN_FAILURE: 'GET_ADMIN_FAILURE',
  //CREATE ADMIN SECTION
  CREATE_ADMIN_START: 'CREATE_ADMIN_START',
  CREATE_ADMIN_END: 'CREATE_ADMIN_END',
  CREATE_ADMIN_SUCCESS: 'CREATE_ADMIN_SUCCESS',
  CREATE_ADMIN_FAILURE: 'CREATE_ADMIN_FAILURE',
  //EDIT ADMIN SECTION
  EDIT_ADMIN_START: 'EDIT_ADMIN_START',
  EDIT_ADMIN_END: 'EDIT_ADMIN_END',
  EDIT_ADMIN_SUCCESS: 'EDIT_ADMIN_SUCCESS',
  EDIT_ADMIN_FAILURE: 'EDIT_ADMIN_FAILURE',
  //DELETE ADMIN SECTION
  DELETE_ADMIN_START: 'DELETE_ADMIN_START',
  DELETE_ADMIN_END: 'DELETE_ADMIN_END',
  DELETE_ADMIN_SUCCESS: 'DELETE_ADMIN_SUCCESS',
  DELETE_ADMIN_FAILURE: 'DELETE_ADMIN_FAILURE'
};
