export const categoryActionTypes = {
  //GET CATEGORIES SECTION
  GET_CATEGORIES_START: 'GET_CATEGORIES_START',
  GET_CATEGORIES_END: 'GET_CATEGORIES_END',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE'
};
