export const categoryActionTypes = {
  //GET CATEGORIES SECTION
  GET_CATEGORIES_START: 'GET_CATEGORIES_START',
  GET_CATEGORIES_END: 'GET_CATEGORIES_END',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',
  CREATE_CATEGORY_START: 'CREATE_CATEGORY_START',
  CREATE_CATEGORY_END: 'CREATE_CATEGORY_END',
  CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
  CREATE_CATEGORY_FAILURE: 'CREATE_CATEGORY_FAILURE'
};
