export const categoryActionTypes = {
  //GET CATEGORIES SECTION
  GET_CATEGORIES_START: 'GET_CATEGORIES_START',
  GET_CATEGORIES_END: 'GET_CATEGORIES_END',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',
  GET_CATEGORY_START: 'GET_CATEGORY_START',
  GET_CATEGORY_END: 'GET_CATEGORY_END',
  GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
  GET_CATEGORY_FAILURE: 'GET_CATEGORY_FAILURE',
  CREATE_CATEGORY_START: 'CREATE_CATEGORY_START',
  CREATE_CATEGORY_END: 'CREATE_CATEGORY_END',
  CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
  CREATE_CATEGORY_FAILURE: 'CREATE_CATEGORY_FAILURE',
  EDIT_CATEGORY_START: 'EDIT_CATEGORY_START',
  EDIT_CATEGORY_END: 'EDIT_CATEGORY_END',
  EDIT_CATEGORY_SUCCESS: 'EDIT_CATEGORY_SUCCESS',
  EDIT_CATEGORY_FAILURE: 'EDIT_CATEGORY_FAILURE',
  DELETE_CATEGORY_START: 'DELETE_CATEGORY_START',
  DELETE_CATEGORY_END: 'DELETE_CATEGORY_END',
  DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
  DELETE_CATEGORY_FAILURE: 'DELETE_CATEGORY_FAILURE'
};
