export const categoryActionTypes = {
  //GET CATEGORIES SECTION
  GET_PRODUCTS_START: 'GET_PRODUCTS_START',
  GET_PRODUCTS_END: 'GET_PRODUCTS_END',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILURE: 'GET_PRODUCTS_FAILURE',
  //GET ALL CATEGORIES SECTION
  GET_ALL_PRODUCTS_START: 'GET_ALL_PRODUCTS_START',
  GET_ALL_PRODUCTS_END: 'GET_ALL_PRODUCTS_END',
  GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
  GET_ALL_PRODUCTS_FAILURE: 'GET_ALL_PRODUCTS_FAILURE',
  //GET CATEGORY SECTION
  GET_PRODUCT_START: 'GET_PRODUCT_START',
  GET_PRODUCT_END: 'GET_PRODUCT_END',
  GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
  GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE',
  //CREATE CATEGORY SECTION
  CREATE_PRODUCT_START: 'CREATE_PRODUCT_START',
  CREATE_PRODUCT_END: 'CREATE_PRODUCT_END',
  CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
  CREATE_PRODUCT_FAILURE: 'CREATE_PRODUCT_FAILURE',
  //EDIT CATEGORY SECTION
  EDIT_PRODUCT_START: 'EDIT_PRODUCT_START',
  EDIT_PRODUCT_END: 'EDIT_PRODUCT_END',
  EDIT_PRODUCT_SUCCESS: 'EDIT_PRODUCT_SUCCESS',
  EDIT_PRODUCT_FAILURE: 'EDIT_PRODUCT_FAILURE',
  //DELETE CATEGORY SECTION
  DELETE_PRODUCT_START: 'DELETE_PRODUCT_START',
  DELETE_PRODUCT_END: 'DELETE_PRODUCT_END',
  DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
  DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE'
};
