export const userActionTypes = {
  //CLEAR STORE
  CLEAR_USER_STORE: 'CLEAR_USER_STORE',
  //LOGIN SECTION
  LOGIN_USER_START: 'LOGIN_USER_START',
  LOGIN_USER_END: 'LOGIN_USER_END',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
  //FORGOT_PASSWORD SECTION
  FORGOT_PASSWORD_START: 'FORGOT_PASSWORD_START',
  FORGOT_PASSWORD_END: 'FORGOT_PASSWORD_END',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',
  //RESET_PASSWORD SECTION
  RESET_PASSWORD_START: 'RESET_PASSWORD_START',
  RESET_PASSWORD_END: 'RESET_PASSWORD_END',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',
  //ACTIVATE_ACCOUNT SECTION
  ACTIVATE_ACCOUNT_START: 'ACTIVATE_ACCOUNT_START',
  ACTIVATE_ACCOUNT_END: 'ACTIVATE_ACCOUNT_END',
  ACTIVATE_ACCOUNT_SUCCESS: 'ACTIVATE_ACCOUNT_SUCCESS',
  ACTIVATE_ACCOUNT_FAILURE: 'ACTIVATE_ACCOUNT_FAILURE'
};
